version: '3.5'

services:
  job-cluster:
    build: .
    container_name: job-cluster
    ports:
      - 8081:8081
      - 9249:9249
    volumes:
      - state:/state
    command: /opt/flink/bin/standalone-job.sh start-foreground --job-classname ut.bigdata.heatmap.HeatmapProcess --job-id 00000000000000000000000000000000 -Djobmanager.rpc.address=job-cluster -Dstate.checkpoints.dir=file:///state
    networks:
      - proxynet

  taskmanager1:
    build: .
    container_name: taskmanager1
    ports:
      - 9250:9249
    volumes:
      - state:/state
    command: /opt/flink/bin/taskmanager.sh start-foreground -Djobmanager.rpc.address=job-cluster -Dstate.checkpoints.dir=file:///state
    networks:
      - proxynet

  taskmanager2:
    build: .
    container_name: taskmanager2
    ports:
      - 9251:9249
    volumes:
      - state:/state
    command: /opt/flink/bin/taskmanager.sh start-foreground -Djobmanager.rpc.address=job-cluster -Dstate.checkpoints.dir=file:///state
    networks:
      - proxynet

  prometheus:
    image: prom/prometheus:v2.17.1
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - ./config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./config/prometheus/flink.rules.yml:/etc/prometheus/flink.rules.yml
    networks:
      - proxynet

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./config/grafana/provisioning/:/etc/grafana/provisioning/
    networks:
      - proxynet

  influxdb:
    image: influxdb:latest
    container_name: influxdb
    ports:
      - 8086:8086
    environment:
      - INFLUXDB_HTTP_AUTH_ENABLED=true
      - INFLUXDB_DB=sensor_temperatures
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
    volumes:
      - influxdb-storage:/var/lib/influxdb
    networks:
      - proxynet

volumes:
  state:
  influxdb-storage:

networks:
  proxynet:
    name: custom_network
