{
 "title": "Temperature Sensors",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Temperature Measures", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Relation between temperatures IN/OUT per room",
   "type": "heatmap",
   "gridPos": { "h": 15, "w": 18, "x": 1, "y": 1 },
   "targets": [
    {
     "alias": "Room [[tag_room]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "rooms_avg",
     "query": "SELECT \"value\" FROM \"rooms_avg\"  GROUP BY \"room\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Alert Counter",
   "type": "graph",
   "gridPos": { "h": 14, "w": 5, "x": 19, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_operator_veneco",
     "legendFormat": "Alerts"
    }
   ]
  },
  {
   "title": "Room Temperatures IN",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "Room [[tag_room]]",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "rooms_temperatures",
     "query": "SELECT last(\"value\"), room FROM \"rooms_temperatures\" WHERE (\"source\" = 'IN') AND time > now() - 15s GROUP BY \"room\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=", "value": "IN" }
     ]
    }
   ]
  },
  {
   "title": "Room Temperatures OUT",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "Room [[tag_room]]",
     "measurement": "rooms_temperatures",
     "query": "SELECT last(\"value\"), room FROM \"rooms_temperatures\" WHERE (\"source\" = 'OUT') AND time > now() - 15s GROUP BY \"room\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=", "value": "IN" }
     ]
    }
   ]
  },
  { "title": "Performance Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 29 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "expr": "flink_jobmanager_job_uptime{job_name=\"Relation_between_temperatures_IN_OUT_per_room\"}"
    }
   ]
  },
  {
   "title": "Job Manager Memory usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "flink_jobmanager_Status_JVM_Memory_Heap_Used",
     "legendFormat": "heap memory [{{instance}}]"
    },
    {
     "expr": "flink_jobmanager_Status_JVM_Memory_NonHeap_Used",
     "legendFormat": "non-heap memory [{{instance}}]"
    }
   ]
  },
  {
   "title": "Average Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 32 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_operator_fetch_latency_avg",
     "legendFormat": "{{task_name}}"
    }
   ]
  },
  {
   "title": "Task Manager Memory usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "flink_taskmanager_Status_JVM_Memory_Heap_Used",
     "legendFormat": "heap memory [{{instance}}]"
    },
    {
     "expr": "flink_taskmanager_Status_JVM_Memory_NonHeap_Used",
     "legendFormat": "non-heap memory [{{instance}}]"
    }
   ]
  },
  {
   "title": "Average Latency Kafka Consumer",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 41 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_operator_KafkaConsumer_commit_latency_avg"
    }
   ]
  }
 ]
}