version: '3.5'

services:
  zookeeper:
    container_name: zookeeper
    image: bitnami/zookeeper:latest
    ports:
      - 2181:2181
    volumes:
      - zookeeper_data:/bitnami
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - proxynet

  kafka:
    container_name: kafka
    image: bitnami/kafka:latest
    ports:
      - 9092:9092
      - 29092:29092
    volumes:
      - kafka_data:/bitnami
    #      - /path/to/server.properties:/bitnami/kafka/conf/server.properties
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,PLAINTEXT_HOST://:29092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
    depends_on:
      - zookeeper
    networks:
      - proxynet

  kafka_manager:
    container_name: kafka_manager
    image: hlebalbau/kafka-manager:stable
    ports:
      - 9000:9000
    environment:
      - ZK_HOSTS=zookeeper:2181
      - APPLICATION_SECRET=random-secret
    command: -Dpidfile.path=/dev/null
    depends_on:
      - zookeeper
    networks:
      - proxynet

  kafka_consumer_producer:
    build: .
    container_name: kafka_consumer_producer
    depends_on:
      - kafka
    networks:
      - proxynet

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local

networks:
  proxynet:
    name: custom_network
